version: '3.8'

services:
  frontend:
    build: frontend/.
    ports:
      - "5000:5000"
    container_name: frontend
    depends_on:
      - "backend"
  backend:
    build: backend/.
    ports:
      - "8080:8080"
    container_name: backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - "redis"
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: cache