version: '3.8'

services:
  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
  backend:
    build: backend/.
    ports:
      - "5000:5000"
    container_name: backend
    volumes:
      - model:/src/model
    depends_on:
      - training
  training:
    build: training/.
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    container_name: training

volumes:
  model:
  imgs: