version: '3.8'

services:
  frontend:
    build: frontend/.
    ports:
      - "5000:5000"
    container_name: frontend
    depends_on:
      - backend

  backend:
    build: backend/.
    ports:
      - "8080:8080"
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: cache

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db

  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  database: